name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Publish message to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "Status for building and publishing {{ name }}:{{ tag }}: {% raw %}${{ job.status }}{% endraw %}"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false
