
name: EulerPublisher 🚀
on: [push]
jobs:
  
  openeuler:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      
        
      - name: Login to OEPKGS
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OEPKGS_USERNAME }}
          password: ${{ secrets.OEPKGS_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/openeuler/openeuler:24.03-lts
            
            quay.io/openeuler/openeuler:24.03-lts
            
            hub.oepkgs.net/openeuler/openeuler:24.03-lts
            
          file: ${{ github.workspace }}/openeuler/Dockerfile
          context: ${{ github.workspace }}/openeuler
          push: true  
  python:
    
    needs: 
      - openeuler
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      
        
      - name: Login to OEPKGS
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OEPKGS_USERNAME }}
          password: ${{ secrets.OEPKGS_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/openeuler/python:3.9-oe2403lts
            
            quay.io/openeuler/python:3.9-oe2403lts
            
            hub.oepkgs.net/openeuler/python:3.9-oe2403lts
            
          file: ${{ github.workspace }}/python/Dockerfile
          context: ${{ github.workspace }}/python
          push: true  
  cann:
    
    needs: 
      - python
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      
        
      - name: Login to OEPKGS
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OEPKGS_USERNAME }}
          password: ${{ secrets.OEPKGS_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/openeuler/cann:8.0.0.beta1-python3.9-oe2403lts
            
            quay.io/openeuler/cann:8.0.0.beta1-python3.9-oe2403lts
            
            hub.oepkgs.net/openeuler/cann:8.0.0.beta1-python3.9-oe2403lts
            
          file: ${{ github.workspace }}/cann/Dockerfile
          context: ${{ github.workspace }}/cann
          push: true  
  pytorch:
    
    needs: 
      - cann
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      
        
      - name: Login to OEPKGS
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OEPKGS_USERNAME }}
          password: ${{ secrets.OEPKGS_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/openeuler/pytorch:2.5.1-cann8.0.0.beta1-python3.9-oe2403lts
            
            quay.io/openeuler/pytorch:2.5.1-cann8.0.0.beta1-python3.9-oe2403lts
            
            hub.oepkgs.net/openeuler/pytorch:2.5.1-cann8.0.0.beta1-python3.9-oe2403lts
            
          file: ${{ github.workspace }}/pytorch/Dockerfile
          context: ${{ github.workspace }}/pytorch
          push: true