
name: EulerPublisher 🚀
on: [push]
jobs:

  openeuler:
    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/zhihang161013/openeuler:22.03-lts
            
            quay.io/zhihang161013/openeuler:22.03-lts
            
          file: ${{ github.workspace }}/openeuler/Dockerfile
          context: ${{ github.workspace }}/openeuler
          push: true

      - name: Publish message to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{
            "repository": zhihang161013
            "name": openeuler,
            "tag": 22.03-lts
            "status": ${{ job.status }}
          }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false
  python:
    
    needs: 
      - openeuler
    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/zhihang161013/python:3.9.1-oe2203lts
            
            quay.io/zhihang161013/python:3.9.1-oe2203lts
            
          file: ${{ github.workspace }}/python/Dockerfile
          context: ${{ github.workspace }}/python
          push: true

      - name: Publish message to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{
            "repository": zhihang161013
            "name": python,
            "tag": 3.9.1-oe2203lts
            "status": ${{ job.status }}
          }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false
  cann:
    
    needs: 
      - python
    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/zhihang161013/cann:8.0.0.beta1-python3.9.1-oe2203lts
            
            quay.io/zhihang161013/cann:8.0.0.beta1-python3.9.1-oe2203lts
            
          file: ${{ github.workspace }}/cann/Dockerfile
          context: ${{ github.workspace }}/cann
          push: true

      - name: Publish message to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{
            "repository": zhihang161013
            "name": cann,
            "tag": 8.0.0.beta1-python3.9.1-oe2203lts
            "status": ${{ job.status }}
          }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false
  pytorch:
    
    needs: 
      - cann
    
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with: 
          platforms: |
            
            x86_64
            
            aarch64
            
          tags: |
            
            docker.io/zhihang161013/pytorch:2.5.1-cann8.0.0.beta1-python3.9.1-oe2203lts
            
            quay.io/zhihang161013/pytorch:2.5.1-cann8.0.0.beta1-python3.9.1-oe2203lts
            
          file: ${{ github.workspace }}/pytorch/Dockerfile
          context: ${{ github.workspace }}/pytorch
          push: true

      - name: Publish message to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{
            "repository": zhihang161013
            "name": pytorch,
            "tag": 2.5.1-cann8.0.0.beta1-python3.9.1-oe2203lts
            "status": ${{ job.status }}
          }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false