
name: EulerPublisher 🚀
on: [push]
jobs:
  build-cann:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm
          
    
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/cann
            
            quay.io/zhihang161013/cann
            
          file: ${{ github.workspace }}/cann/Dockerfile
          context: ${{ github.workspace }}/cann
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-cann-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-cann:
    runs-on: ubuntu-24.04
    needs:
      - build-cann
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-cann-*
          merge-multiple: true

      
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/cann:8.0.0-python3.9.1-oe2503 \
            $(printf 'zhihang161013/cann@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/cann:8.0.0-python3.9.1-oe2503 \
            $(printf 'zhihang161013/cann@sha256:%s ' *)
          
          echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Notify status to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: |
            {
              "trigger": {
                "type": "Github Actions",
                "timestamp": "${{ env.timestamp }}"
              },
              "artifact": {
                "type": "container",
                "info": {
                  "archs": ["x86_64", "aarch64"],
                  "registries": ["docker.io", "quay.io"],
                  "repository": "zhihang161013",
                  "name": "cann",
                  "version": "8.0.0",
                  "tag": "8.0.0-python3.9.1-oe2503",
                  "status": "${{ job.status }}"
                }
              }
            }
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

  build-pytorch:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm
          
    
    needs: 
      - push-cann
    
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/pytorch
            
            quay.io/zhihang161013/pytorch
            
          file: ${{ github.workspace }}/pytorch/Dockerfile
          context: ${{ github.workspace }}/pytorch
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-pytorch-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-pytorch:
    runs-on: ubuntu-24.04
    needs:
      - build-pytorch
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-pytorch-*
          merge-multiple: true

      
      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}
      
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/pytorch:2.6.0-cann8.0.0-python3.9.1-oe2503 \
            $(printf 'zhihang161013/pytorch@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/pytorch:2.6.0-cann8.0.0-python3.9.1-oe2503 \
            $(printf 'zhihang161013/pytorch@sha256:%s ' *)
          
          echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Notify status to EulerPublisher
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: |
            {
              "trigger": {
                "type": "Github Actions",
                "timestamp": "${{ env.timestamp }}"
              },
              "artifact": {
                "type": "container",
                "info": {
                  "archs": ["x86_64", "aarch64"],
                  "registries": ["docker.io", "quay.io"],
                  "repository": "zhihang161013",
                  "name": "pytorch",
                  "version": "2.6.0",
                  "tag": "2.6.0-cann8.0.0-python3.9.1-oe2503",
                  "status": "${{ job.status }}"
                }
              }
            }
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

