
name: EulerPublisher 🚀
on: [push]
jobs:
  build-openeuler:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm64
          
    
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/openeuler
            
            quay.io/zhihang161013/openeuler
            
          file: ${{ github.workspace }}/openeuler/Dockerfile
          context: ${{ github.workspace }}/openeuler
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-openeuler-
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-openeuler:
    runs-on: ubuntu-24.04
    needs:
      
      - build-openeuler-x86_64
      
      - build-openeuler-aarch64
      
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-openeuler-*
          merge-multiple: true

      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/openeuler:25.03 \
            $(printf 'zhihang161013/openeuler@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/openeuler:25.03 \
            $(printf 'zhihang161013/openeuler@sha256:%s ' *)
          

      - name: Check status
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{ \"repository\": \"zhihang161013\", \"name\": \"openeuler\", \"tag\": \"25.03\", \"status\": \"${{ job.status }}\" }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

            build-python:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm64
          
    
    needs: 
      - push-openeuler
    
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/python
            
            quay.io/zhihang161013/python
            
          file: ${{ github.workspace }}/python/Dockerfile
          context: ${{ github.workspace }}/python
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-python-
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-python:
    runs-on: ubuntu-24.04
    needs:
      
      - build-python-x86_64
      
      - build-python-aarch64
      
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-python-*
          merge-multiple: true

      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/python:3.9.1-oe2503 \
            $(printf 'zhihang161013/python@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/python:3.9.1-oe2503 \
            $(printf 'zhihang161013/python@sha256:%s ' *)
          

      - name: Check status
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{ \"repository\": \"zhihang161013\", \"name\": \"python\", \"tag\": \"3.9.1-oe2503\", \"status\": \"${{ job.status }}\" }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

            build-cann:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm64
          
    
    needs: 
      - push-python
    
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/cann
            
            quay.io/zhihang161013/cann
            
          file: ${{ github.workspace }}/cann/Dockerfile
          context: ${{ github.workspace }}/cann
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-cann-
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-cann:
    runs-on: ubuntu-24.04
    needs:
      
      - build-cann-x86_64
      
      - build-cann-aarch64
      
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-cann-*
          merge-multiple: true

      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/cann:8.0.0.alpha001-python3.9.1-oe2503 \
            $(printf 'zhihang161013/cann@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/cann:8.0.0.alpha001-python3.9.1-oe2503 \
            $(printf 'zhihang161013/cann@sha256:%s ' *)
          

      - name: Check status
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{ \"repository\": \"zhihang161013\", \"name\": \"cann\", \"tag\": \"8.0.0.alpha001-python3.9.1-oe2503\", \"status\": \"${{ job.status }}\" }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

            build-pytorch:
    strategy:
      matrix:
        include:
          
          - arch: x86_64
            runner: ubuntu-24.04
          
          - arch: aarch64
            runner: ubuntu-24.04-arm64
          
    
    needs: 
      - push-cann
    
    runs-on: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        uses: docker/build-push-action@v6
        id: build
        with: 
          platforms: ${{ matrix.arch }}
          tags: |
            
            docker.io/zhihang161013/pytorch
            
            quay.io/zhihang161013/pytorch
            
          file: ${{ github.workspace }}/pytorch/Dockerfile
          context: ${{ github.workspace }}/pytorch
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-pytorch-
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  push-pytorch:
    runs-on: ubuntu-24.04
    needs:
      
      - build-pytorch-x86_64
      
      - build-pytorch-aarch64
      
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-pytorch-*
          merge-multiple: true

      
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
        
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
        
      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          
          docker buildx imagetools create -t docker.io/zhihang161013/pytorch:2.4.1-cann8.0.0.alpha001-python3.9.1-oe2503 \
            $(printf 'zhihang161013/pytorch@sha256:%s ' *)
          
          docker buildx imagetools create -t quay.io/zhihang161013/pytorch:2.4.1-cann8.0.0.alpha001-python3.9.1-oe2503 \
            $(printf 'zhihang161013/pytorch@sha256:%s ' *)
          

      - name: Check status
        uses: eferraris/rabbit-sender@v1
        with:
          MESSAGE: "{ \"repository\": \"zhihang161013\", \"name\": \"pytorch\", \"tag\": \"2.4.1-cann8.0.0.alpha001-python3.9.1-oe2503\", \"status\": \"${{ job.status }}\" }"
          RABBIT_EXCHANGE_NAME: "eulerpublisher"
          ROUTING_KEY: "tracker"
          RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
          RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          RABBIT_PORT: 5672
          RABBIT_USE_SSL: false
          DURABLE: false

          